export const APIS = {
  LOGIN: "/login",
  NODES: {
    ADD_DATA_NODE: "/frac/addDataNode",
    ADD_DATA_NODES: "/frac/addDataNodes",
    GET_ALL_NODES_FOR_TYPE: "/frac/getAllNodes?type=",
    GET_ALL_NODES_FOR_DEPARTMENT: "&department=",
    GET_NODE_BY_ID_ONE: "/frac/getNodeById?id=",
    GET_NODE_BY_ID_TWO: "&type=",
    MAP_NODES: "/frac/mapNodes",
    GET_CHILD_NODES_FOR_PARENT_ONE: "/frac/getChildNodes?parentId=",
    GET_CHILD_NODES_FOR_PARENT_TWO: "&type=",
    SEARCH_NODES: "/frac/searchNodes",
    APPEND_MAP_NODES: "/frac/appendMapNodes",
    GET_PARENT_NODE_ONE: "/frac/getParentNodes?childId=",
    GET_PARENT_NODE_TWO: "&type=",
    EXPLORE_ALL_NODES: "/frac/exploreAllNodes",
    EXPLORE_ALL_NODES_DEPT: "?department=",
    SEARCH_NODES_EXPLORE_DEPT: "&department=",
    SEARCH_NODES_EXPLORE: "/frac/exploreSearch?keyword=",
    DELETE_NODE_ONE: "/frac/deleteNode?id=",
    DELETE_NODE_TWO: "&type=",
    COMMENT_NODE: "/frac/commentNode",
    GET_COMMENT_ONE: "/frac/getNodeComments?type=",
    GET_COMMENT_TWO: "&id=",
    GET_NODE_RATING_ONE: "/frac/getNodeRating?type=",
    GET_NODE_RATING_TWO: "&id=",
    RATE_NODE: "/frac/rateNode",
    GET_AVERAGE_RATING_ONE: "/frac/getNodeRatingAverage?type=",
    GET_AVERAGE_RATING_TWO: "&id=",
    GET_COMPETENCY_AREA_LISTING: "/frac/getCompetencyAreaListing",
    FILTER_NODES: "/frac/filterNodes",
    GET_ACTIVITY_LOGS_ID: "/frac/getCollectionLogs?id=",
    GET_ACTIVITY_LOGS_TYPE: "&type=",
    CREATE_BULK_NODE: "/frac/addDataNodeBulk",
    GET_SOURCE_LIST: "/frac/getSourceList?type=",
    GET_PROPERTY_COUNT_LIST: "/frac/getPropertyCountList?type=",
  },
  DASHBOARD: "/frac/getCountOfNodes?type=",
  COUNT_BY_DEPT: "&department=",
  GET_BY_STATUS: "&status=",
  KEYCLOAK_WTOKEN: "/realms/sunbird/protocol/openid-connect/token",
  KEYCLOAK_RESET: "apis/reset",
  KEYCLOAK_LOGOUT_ONE:
    "assets/configurations/d136953gtttd92.cloudfront.net/host.config.json",
  KEYCLOAK_LOGOUT: "auth/realms/wingspan/protocol/openid-connect/logout",
  CLOUD_STORAGE: "/frac/cloudStorage",
  DELETE_CLOUD_FILE: "/frac/deleteCloudFile?fileName=",
  REVIEW: {
    GET_VERIFICATION_LIST: "/frac/getVerificationList?type=",
    VERIFY: "/frac/verifyDataNode",
    GET_SIMILAR: "/frac/getNodeById?id=",
    GET_SIMILAR_TWO: "&type=",
    GET_SIMILAR_THREE: "&showSimilar=",
    USER_TYPE: "&userType=",
    FILTER_REVIEW_NODE: "/frac/filterReviewNodes",
  },
  DEPARTMENTS: {
    GET_ALL_DEPARTMENTS: "/api/org/v1/search"
  },
  FEEDBACK: {
    POST_NODE_FEEDBACK: "/frac/nodeFeedback",
    GET_NODE_FEEDBACK: "/frac/getNodeFeedback?type=",
    NODE_USER: "&user="
  },
  GET_USER_ROLES: "/api/user/v1/read/",
  SESSION: {
    CREATE: "/api/fracSession/create",
    DELETE: "/api/fracSession/delete",
    GET_ALL_SESSIONS: "/api/fracSession/getAll",
  },
  CHARTS: {
    GET_REVIEW_CHART: "/frac/getMyGraphs?visualizationCode="
  }
};
