// import { APP } from "./../constants";

export const ROLES = {
  FRACADMIN: {
    routes: [
      "/",
      "/dashboard",
      "/explore",
      "/collections",
      "/collection-positions",
      "/collection-roles",
      "/collection-activities",
      "/collection-competencies",
      "/collection-knowledge-resources",
      "/review",
      "/review/position",
      "/review/role",
      "/review/activity",
      "/review/competency",
      "/release-notes",
      "/walkthrough",
      "/admin",
      "/workflow-dashboard",
      "/workflow-people",
      "/workflow-detail",
      "/level",
      "/faq"
    ],
  },
  IFUUSER: {
    routes: [
      "/",
      "/dashboard",
      "/explore",
      "/collections",
      "/collection-positions",
      "/collection-roles",
      "/collection-activities",
      "/collection-competencies",
      "/collection-knowledge-resources",
      "/release-notes",
      "/walkthrough",
    ],
  },
  FRACREVIEWERONE: {
    routes: [
      "/",
      "/dashboard",
      "/explore",
      "/release-notes",
      "/walkthrough",
      "/review",
      "/review/position",
      "/review/role",
      "/review/activity",
      "/review/competency",
      "/faq",
      "/collections",
      "/collection-positions",
      "/collection-roles",
      "/collection-activities",
      "/collection-competencies",
      "/collection-knowledge-resources",
    ],
  },
  FRACREVIEWERTWO: {
    routes: [
      "/",
      "/dashboard",
      "/explore",
      "/release-notes",
      "/walkthrough",
      "/review",
      "/review/position",
      "/review/role",
      "/review/activity",
      "/review/competency",
      "/faq",
      "/collections",
      "/collection-positions",
      "/collection-roles",
      "/collection-activities",
      "/collection-competencies",
      "/collection-knowledge-resources",
    ],
  },
  FRACACCESSCOMPETENCY: {
    routes: [
      "/",
      "/dashboard",
      "/release-notes",
      "/walkthrough",
      "/collections",
      "/collection-competencies",
    ],
  },
};
